import type { ChecklistItem, FlightItinerary, JourneyResult, RecommendationReason, TravelAlert, TripDetails, TripPreferences, TravelerData, VisaRequirement } from '../types/trip';
import { buildVisaRequirements } from './aiService';
import { searchRealFlights } from './flightService';

const duration=(m:number)=>`${Math.floor(m/60)}h ${m%60}m`;
const safeVisa=(requirements:VisaRequirement[])=>!requirements.some(v=>v.status==='visa_required'||v.status==='transit_visa');
function choosePrimary(flights:FlightItinerary[], requirements:VisaRequirement[], prefs:TripPreferences):FlightItinerary{
  const minPrice=Math.min(...flights.map(f=>f.price)); const minDuration=Math.min(...flights.map(f=>f.totalDurationMinutes));
  return [...flights].sort((a,b)=>{
    const score=(f:FlightItinerary)=>{
      const price=(f.price/minPrice)*45; const time=(f.totalDurationMinutes/minDuration)*25; const stops=f.layovers.length*8; const long=f.layovers.filter(l=>l.durationMinutes>prefs.maximumLayoverHours*60).length*12; const emissions=Math.max(0,f.carbonEmissions?.differencePercent??0)*0.15; return price+time+stops+long+emissions-(safeVisa(requirements)?5:0);
    }; return score(a)-score(b);
  })[0];
}
function reasons(primary:FlightItinerary, flights:FlightItinerary[], visa:VisaRequirement[]):RecommendationReason[]{
  const result:RecommendationReason[]=[]; const cheapest=Math.min(...flights.map(f=>f.price)); const fastest=Math.min(...flights.map(f=>f.totalDurationMinutes));
  result.push({icon:'price',title:primary.price===cheapest?'Lowest fare':'Strong value',detail:primary.price===cheapest?'This is the lowest current fare returned.':`Only ${primary.price-cheapest} more than the cheapest option for a better overall itinerary.`});
  result.push({icon:'time',title:primary.totalDurationMinutes===fastest?'Fastest option':'Balanced travel time',detail:`Total journey time is ${duration(primary.totalDurationMinutes)}.`});
  result.push({icon:'visa',title:safeVisa(visa)?'Simpler visa path':'Visa action needed',detail:safeVisa(visa)?'The local passport dataset does not flag a destination or planned-stop visa requirement.':'Review the visa warnings before booking.'});
  if(primary.layovers.length) result.push({icon:'layover',title:`${primary.layovers.length} connection${primary.layovers.length>1?'s':''}`,detail:primary.layovers.map(l=>`${l.airportCode} ${duration(l.durationMinutes)}`).join(' • ')});
  if(primary.carbonEmissions) result.push({icon:'emissions',title:primary.carbonEmissions.differencePercent<=0?'Lower emissions':'Emissions comparison',detail:`${Math.abs(primary.carbonEmissions.differencePercent)}% ${primary.carbonEmissions.differencePercent<=0?'below':'above'} the route average.`});
  return result.slice(0,5);
}
function alerts(primary:FlightItinerary, visa:VisaRequirement[], trip:TripDetails):TravelAlert[]{ const a:TravelAlert[]=[]; visa.filter(v=>v.status==='visa_required'||v.status==='transit_visa').forEach(v=>a.push({severity:'critical',title:`Check ${v.countryName} visa rules`,detail:v.note})); primary.layovers.filter(l=>l.durationMinutes<75).forEach(l=>a.push({severity:'warning',title:`Tight connection at ${l.airportCode}`,detail:`The connection is ${duration(l.durationMinutes)}. Confirm minimum connection time and terminal changes.`})); primary.layovers.filter(l=>l.durationMinutes>480).forEach(l=>a.push({severity:'info',title:`Long layover at ${l.airportCode}`,detail:`The connection is ${duration(l.durationMinutes)}. Check whether leaving the airport changes transit requirements.`})); if(trip.budget>0&&primary.price>trip.budget) a.push({severity:'warning',title:'Above your stated budget',detail:`The live fare is ${primary.price-trip.budget} over budget.`}); return a; }
function checklist(visa:VisaRequirement[], prefs:TripPreferences):ChecklistItem[]{ const needsVisa=visa.some(v=>v.status==='visa_required'||v.status==='transit_visa'||v.status==='evisa'); return [{id:'passport',label:'Passport',detail:'Check validity and blank-page requirements',required:true},{id:'visa',label:'Visa or travel authorization',detail:needsVisa?'Action may be required before travel':'Keep official rule confirmation',required:needsVisa},{id:'onward',label:'Onward or return ticket',detail:'May be requested at check-in or immigration',required:true},{id:'hotel',label:'Accommodation confirmation',detail:'Keep the address available offline',required:true},{id:'insurance',label:'Travel insurance',detail:'Recommended for medical and disruption coverage',required:false},{id:'bags',label:'Baggage allowance',detail:prefs.checkedBaggage?'Confirm checked-bag fees and limits':'Confirm carry-on size and weight',required:true}]; }
export async function buildJourneyResult(traveler:TravelerData,trip:TripDetails,prefs:TripPreferences):Promise<JourneyResult>{ const live=await searchRealFlights(traveler,trip,prefs); const all=[...live.bestFlights,...live.otherFlights]; if(!all.length) throw new Error('No live itineraries were returned.'); const visa=buildVisaRequirements(traveler,trip); const primary=choosePrimary(all,visa,prefs); const alternatives=all.filter(f=>f.id!==primary.id).slice(0,8); const rs=reasons(primary,all,visa); return {recommendation:{label:'FlightADVSR Pick',headline:`${primary.segments[0]?.airline??'Recommended itinerary'} offers the best balance for this trip.`,explanation:`This recommendation compares live price, total duration, connections, emissions when available, and the visa checks tied to your passport and route.`,reasons:rs},primaryFlight:primary,alternativeFlights:alternatives,priceInsights:live.priceInsights,airportMetadata:live.airports,visaRequirements:visa,requiredDocuments:['Passport','Onward or return ticket','Accommodation confirmation',...(visa.some(v=>v.status!=='visa_free')?['Visa or travel authorization']:[])],checklist:checklist(visa,prefs),travelAlerts:alerts(primary,visa,trip),destinationInsights:[{label:'Destination',value:trip.destination?.country??'Unknown',icon:'globe-outline'},{label:'Trip type',value:trip.tripMode==='round_trip'?'Round trip':'One way',icon:'repeat-outline'},{label:'Cabin',value:prefs.cabinClass.replace('_',' '),icon:'airplane-outline'}],currency:trip.currency||'USD',generatedAt:new Date().toISOString(),isLiveData:true}; }
